[2022-09-19 19:28:23,663: INFO: stage_01_load_save]: 
********************
[2022-09-19 19:28:23,664: INFO: stage_01_load_save]: >>>>> stage Get Data started <<<<<
[2022-09-19 19:28:23,683: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-19 19:28:23,684: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-19 19:28:23,684: INFO: common]: json file: config.json loaded successfully
[2022-09-19 19:29:42,184: INFO: stage_01_load_save]: >>>>> stage Get Data completed!<<<<<

[2022-09-19 19:41:35,825: INFO: stage_01_load_save]: 
********************
[2022-09-19 19:41:35,825: INFO: stage_01_load_save]: >>>>> stage Get Data started <<<<<
[2022-09-19 19:41:35,839: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-19 19:41:35,841: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-19 19:41:35,841: INFO: common]: json file: config.json loaded successfully
[2022-09-19 19:56:00,863: INFO: stage_01_load_save]: 
********************
[2022-09-19 19:56:00,863: INFO: stage_01_load_save]: >>>>> stage Get and Save Data started <<<<<
[2022-09-19 19:56:00,866: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-19 19:56:00,867: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-19 20:02:23,819: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-19 20:03:07,281: INFO: stage_01_load_save]: raw data is saved at: artifacts\raw_local_dir\data.csv successfully
[2022-09-19 20:03:07,485: INFO: stage_01_load_save]: >>>>> stage Get and Save Data completed!<<<<<

[2022-09-19 20:17:59,819: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-19 20:17:59,819: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-19 20:17:59,820: ERROR: stage_01_load_n_save_data]: main() missing 1 required positional argument: 'json_path'
Traceback (most recent call last):
  File "src/stage_01_load_n_save_data.py", line 49, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
TypeError: main() missing 1 required positional argument: 'json_path'
[2022-09-19 20:19:04,778: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-19 20:19:04,778: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-19 20:19:04,778: ERROR: stage_01_load_n_save_data]: main() missing 1 required positional argument: 'json_path'
Traceback (most recent call last):
  File "src/stage_01_load_n_save_data.py", line 49, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
TypeError: main() missing 1 required positional argument: 'json_path'
[2022-09-19 20:24:23,176: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-19 20:24:23,176: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-19 20:24:23,194: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-19 20:24:23,196: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-19 20:31:08,179: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-19 20:31:26,263: INFO: stage_01_load_n_save_data]: raw data is saved at: artifacts\raw_local_dir\data.csv successfully
[2022-09-19 20:31:26,317: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data completed!<<<<<

[2022-09-21 14:36:54,120: INFO: stage_02_data_preprocessing]: 
********************
[2022-09-21 14:36:54,120: INFO: stage_02_data_preprocessing]: >>>>> stage Data Preprocessing started <<<<<
[2022-09-21 14:36:54,141: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-21 14:36:54,151: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-21 14:36:54,176: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-21 14:36:59,769: INFO: clientbase]: Created a worker pool for first use
[2022-09-21 14:37:05,623: INFO: run]: Could not load the run context. Logging offline
[2022-09-21 14:37:05,623: INFO: stage_02_data_preprocessing]: fetched the data from : artifacts\raw_local_dir\data.csv
[2022-09-21 14:37:12,560: INFO: stage_02_data_preprocessing]: Dropped last row
[2022-09-21 14:37:12,946: ERROR: stage_02_data_preprocessing]: Cannot convert non-finite values (NA or inf) to integer
Traceback (most recent call last):
  File "src/stage_02_data_preprocessing.py", line 107, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_data_preprocessing.py", line 56, in main
    df[col_name] = df[col_name].astype(int)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\internals\managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\internals\managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\internals\blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\dtypes\cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\dtypes\cast.py", line 1257, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\dtypes\cast.py", line 1168, in astype_nansafe
    return astype_float_to_int_nansafe(arr, dtype, copy)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\dtypes\cast.py", line 1214, in astype_float_to_int_nansafe
    "Cannot convert non-finite values (NA or inf) to integer"
pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer
[2022-09-21 14:53:08,500: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-21 14:53:08,501: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-21 14:53:08,521: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-21 14:53:08,527: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-21 14:54:19,880: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-21 14:54:41,101: INFO: stage_01_load_n_save_data]: raw data is saved at: artifacts\raw_local_dir\data.csv successfully
[2022-09-21 14:54:41,181: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data completed!<<<<<

[2022-09-21 14:55:33,934: INFO: stage_02_data_preprocessing]: 
********************
[2022-09-21 14:55:33,934: INFO: stage_02_data_preprocessing]: >>>>> stage Data Preprocessing started <<<<<
[2022-09-21 14:55:33,941: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-21 14:55:33,948: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-21 14:55:33,951: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-21 14:55:50,631: INFO: clientbase]: Created a worker pool for first use
[2022-09-21 14:55:58,915: INFO: run]: Could not load the run context. Logging offline
[2022-09-21 14:55:58,915: INFO: stage_02_data_preprocessing]: fetched the data from : artifacts\raw_local_dir\data.csv
[2022-09-21 14:56:08,835: INFO: stage_02_data_preprocessing]: Dropped last row
[2022-09-21 14:56:08,853: INFO: stage_02_data_preprocessing]:          sku  national_inv  lead_time  in_transit_qty  ...  ppap_risk  stop_auto_buy  rev_stop  went_on_backorder
0  1026827.0           0.0        NaN             0.0  ...      False           True     False              False
1  1043384.0           2.0        9.0             0.0  ...      False           True     False              False
2  1043696.0           2.0        NaN             0.0  ...      False           True     False              False
3  1043852.0           7.0        8.0             0.0  ...      False           True     False              False
4  1044048.0           8.0        NaN             0.0  ...      False           True     False              False
5  1044198.0          13.0        8.0             0.0  ...      False           True     False              False
6  1044643.0        1095.0        NaN             0.0  ...      False           True     False              False
7  1045098.0           6.0        2.0             0.0  ...       True           True     False              False
8  1045815.0         140.0        NaN             0.0  ...      False           True     False              False
9  1045867.0           4.0        8.0             0.0  ...      False           True     False              False

[10 rows x 23 columns]
[2022-09-21 14:56:09,921: ERROR: stage_02_data_preprocessing]: Cannot convert non-finite values (NA or inf) to integer
Traceback (most recent call last):
  File "src/stage_02_data_preprocessing.py", line 110, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_data_preprocessing.py", line 59, in main
    df[col_name] = df[col_name].astype(int)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\internals\managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\internals\managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\internals\blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\dtypes\cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\dtypes\cast.py", line 1257, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\dtypes\cast.py", line 1168, in astype_nansafe
    return astype_float_to_int_nansafe(arr, dtype, copy)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\dtypes\cast.py", line 1214, in astype_float_to_int_nansafe
    "Cannot convert non-finite values (NA or inf) to integer"
pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer
[2022-09-21 16:01:47,129: INFO: stage_02_data_preprocessing]: 
********************
[2022-09-21 16:01:47,135: INFO: stage_02_data_preprocessing]: >>>>> stage Data Preprocessing started <<<<<
[2022-09-21 16:01:47,152: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-21 16:01:47,157: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-21 16:01:47,189: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-21 16:01:54,700: INFO: clientbase]: Created a worker pool for first use
[2022-09-21 16:01:58,366: INFO: run]: Could not load the run context. Logging offline
[2022-09-21 16:01:58,366: INFO: stage_02_data_preprocessing]: fetched the data from : artifacts\raw_local_dir\data.csv
[2022-09-21 16:02:05,421: INFO: stage_02_data_preprocessing]: Dropped last row
[2022-09-21 16:02:05,422: INFO: stage_02_data_preprocessing]:          sku  national_inv  lead_time  in_transit_qty  ...  ppap_risk  stop_auto_buy  rev_stop  went_on_backorder
0  1026827.0           0.0        NaN             0.0  ...      False           True     False              False
1  1043384.0           2.0        9.0             0.0  ...      False           True     False              False
2  1043696.0           2.0        NaN             0.0  ...      False           True     False              False
3  1043852.0           7.0        8.0             0.0  ...      False           True     False              False
4  1044048.0           8.0        NaN             0.0  ...      False           True     False              False
5  1044198.0          13.0        8.0             0.0  ...      False           True     False              False
6  1044643.0        1095.0        NaN             0.0  ...      False           True     False              False
7  1045098.0           6.0        2.0             0.0  ...       True           True     False              False
8  1045815.0         140.0        NaN             0.0  ...      False           True     False              False
9  1045867.0           4.0        8.0             0.0  ...      False           True     False              False

[10 rows x 23 columns]
[2022-09-21 16:02:06,467: ERROR: stage_02_data_preprocessing]: Cannot convert non-finite values (NA or inf) to integer
Traceback (most recent call last):
  File "src/stage_02_data_preprocessing.py", line 110, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_data_preprocessing.py", line 59, in main
    df[col_name] = df[col_name].astype(int)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\internals\managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\internals\managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\internals\blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\dtypes\cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\dtypes\cast.py", line 1257, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\dtypes\cast.py", line 1168, in astype_nansafe
    return astype_float_to_int_nansafe(arr, dtype, copy)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\dtypes\cast.py", line 1214, in astype_float_to_int_nansafe
    "Cannot convert non-finite values (NA or inf) to integer"
pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer
[2022-09-21 16:09:19,236: INFO: stage_02_data_preprocessing]: 
********************
[2022-09-21 16:09:19,249: INFO: stage_02_data_preprocessing]: >>>>> stage Data Preprocessing started <<<<<
[2022-09-21 16:09:19,271: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-21 16:09:19,275: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-21 16:09:19,276: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-21 16:09:26,289: INFO: clientbase]: Created a worker pool for first use
[2022-09-21 16:09:30,035: INFO: run]: Could not load the run context. Logging offline
[2022-09-21 16:09:30,036: INFO: stage_02_data_preprocessing]: fetched the data from : artifacts\raw_local_dir\data.csv
[2022-09-21 16:09:37,528: INFO: stage_02_data_preprocessing]: Dropped last row
[2022-09-21 16:09:39,769: INFO: stage_02_data_preprocessing]: Converted columns to 0's and 1's
[2022-09-21 16:09:40,124: INFO: stage_02_data_preprocessing]: Dropped non imp features from the dataset
[2022-09-21 16:09:40,178: INFO: stage_02_data_preprocessing]: Replacing perf_6_month_avg and perf_12_month_avg with nan values
[2022-09-21 16:09:40,300: INFO: stage_02_data_preprocessing]: Splitting the dataset into X and y
[2022-09-21 16:09:40,315: ERROR: stage_02_data_preprocessing]: '<' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "src/stage_02_data_preprocessing.py", line 108, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_data_preprocessing.py", line 73, in main
    imp.fit(X)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\sklearn\impute\_iterative.py", line 775, in fit
    self.fit_transform(X)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\sklearn\impute\_iterative.py", line 602, in fit_transform
    if self.tol < 0:
TypeError: '<' not supported between instances of 'str' and 'int'
[2022-09-21 16:15:01,999: INFO: stage_02_data_preprocessing]: 
********************
[2022-09-21 16:15:01,999: INFO: stage_02_data_preprocessing]: >>>>> stage Data Preprocessing started <<<<<
[2022-09-21 16:15:02,003: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-21 16:15:02,006: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-21 16:15:02,008: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-21 16:15:07,498: INFO: clientbase]: Created a worker pool for first use
[2022-09-21 16:15:13,381: INFO: run]: Could not load the run context. Logging offline
[2022-09-21 16:15:13,381: INFO: stage_02_data_preprocessing]: fetched the data from : artifacts\raw_local_dir\data.csv
[2022-09-21 16:15:20,617: INFO: stage_02_data_preprocessing]: Dropped last row
[2022-09-21 16:15:22,888: INFO: stage_02_data_preprocessing]: Converted columns to 0's and 1's
[2022-09-21 16:15:23,175: INFO: stage_02_data_preprocessing]: Dropped non imp features from the dataset
[2022-09-21 16:15:23,415: INFO: stage_02_data_preprocessing]: Replacing perf_6_month_avg and perf_12_month_avg with nan values
[2022-09-21 16:15:23,608: INFO: stage_02_data_preprocessing]: Splitting the dataset into X and y
[2022-09-21 16:19:12,467: INFO: stage_02_data_preprocessing]: Filled missing values for lead_time, perf_6_month_avg and perf_12_month_avg columns
[2022-09-21 16:19:13,451: INFO: stage_02_data_preprocessing]: Applying cuberoot for normally distributed data
[2022-09-21 16:19:13,452: ERROR: stage_02_data_preprocessing]: local variable 'SMOTEENN' referenced before assignment
Traceback (most recent call last):
  File "src/stage_02_data_preprocessing.py", line 109, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_data_preprocessing.py", line 84, in main
    SMOTEENN = SMOTEENN(n_jobs=-1)
UnboundLocalError: local variable 'SMOTEENN' referenced before assignment
[2022-09-21 16:29:28,137: INFO: stage_02_data_preprocessing]: 
********************
[2022-09-21 16:29:28,138: INFO: stage_02_data_preprocessing]: >>>>> stage Data Preprocessing started <<<<<
[2022-09-21 16:29:28,155: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-21 16:29:28,160: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-21 16:29:28,161: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-21 16:29:31,830: INFO: clientbase]: Created a worker pool for first use
[2022-09-21 16:29:34,041: INFO: run]: Could not load the run context. Logging offline
[2022-09-21 16:29:34,041: INFO: stage_02_data_preprocessing]: fetched the data from : artifacts\raw_local_dir\data.csv
[2022-09-21 16:29:37,666: INFO: stage_02_data_preprocessing]: Dropped last row
[2022-09-21 16:29:38,610: INFO: stage_02_data_preprocessing]: Converted columns to 0's and 1's
[2022-09-21 16:29:38,900: INFO: stage_02_data_preprocessing]: Dropped non imp features from the dataset
[2022-09-21 16:29:38,936: INFO: stage_02_data_preprocessing]: Replacing perf_6_month_avg and perf_12_month_avg with nan values
[2022-09-21 16:29:39,005: INFO: stage_02_data_preprocessing]: Splitting the dataset into X and y
[2022-09-21 16:33:01,565: INFO: stage_02_data_preprocessing]: Filled missing values for lead_time, perf_6_month_avg and perf_12_month_avg columns
[2022-09-21 16:33:02,438: INFO: stage_02_data_preprocessing]: Applying cuberoot for normally distributed data
[2022-09-21 16:51:26,641: INFO: stage_02_data_preprocessing]: Applied Smoteen to handle imbalanceness of data
[2022-09-21 16:52:25,438: INFO: stage_02_data_preprocessing]: Saved the prep data to: artifacts\raw_local_dir\furnished_data.csv
[2022-09-21 16:52:25,560: INFO: stage_02_data_preprocessing]: >>>>> stage Data Preprocessing completed!<<<<<

[2022-09-22 12:54:12,184: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-22 12:54:12,184: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-22 12:54:12,199: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 12:54:12,204: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 12:55:28,975: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-22 12:55:45,780: INFO: stage_01_load_n_save_data]: raw data is saved at: artifacts\raw_local_dir\data.csv successfully
[2022-09-22 12:55:45,819: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data completed!<<<<<

[2022-09-22 12:56:23,768: INFO: stage_02_data_preprocessing]: 
********************
[2022-09-22 12:56:23,768: INFO: stage_02_data_preprocessing]: >>>>> stage Data Preprocessing started <<<<<
[2022-09-22 12:56:23,770: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 12:56:23,772: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 12:56:23,786: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-22 12:56:29,259: INFO: clientbase]: Created a worker pool for first use
[2022-09-22 12:56:40,015: ERROR: stage_02_data_preprocessing]: SnapshotException:
	Message: Failed to take a snapshot of .. Pass snapshot_directory=None to start_logging to skip taking a snapshot of the given directory.
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Failed to take a snapshot of .. Pass snapshot_directory=None to start_logging to skip taking a snapshot of the given directory."
    }
}
Traceback (most recent call last):
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\run.py", line 609, in _start_logging
    run.take_snapshot(snapshot_directory)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\run.py", line 2201, in take_snapshot
    return self._client.take_snapshot(file_or_folder_path)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_run_impl\run_history_facade.py", line 706, in take_snapshot
    raise_on_validation_failure=_raise_on_validation_failure)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\snapshots_client.py", line 87, in create_snapshot
    self._validate_snapshot_size(file_or_folder_path, exclude_function, raise_on_validation_failure)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\snapshots_client.py", line 65, in _validate_snapshot_size
    raise SnapshotException(error_message)
azureml.exceptions._azureml_exception.SnapshotException: SnapshotException:
	Message: ====================================================================

While attempting to take snapshot of .
Your total snapshot size exceeds the limit of 300.0 MB.
Please see http://aka.ms/aml-largefiles on how to work with large files.

====================================================================


	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "====================================================================\n\nWhile attempting to take snapshot of .\nYour total snapshot size exceeds the limit of 300.0 MB.\nPlease see http://aka.ms/aml-largefiles on how to work with large files.\n\n====================================================================\n\n"
    }
}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/stage_02_data_preprocessing.py", line 115, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_data_preprocessing.py", line 44, in main
    run = experiment.start_logging()
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\experiment.py", line 279, in start_logging
    return Run._start_logging(self, *args, _parent_logger=self._logger, **kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\run.py", line 613, in _start_logging
    raise_from(SnapshotException(error_msg), snapshot_ex)
  File "<string>", line 3, in raise_from
azureml.exceptions._azureml_exception.SnapshotException: SnapshotException:
	Message: Failed to take a snapshot of .. Pass snapshot_directory=None to start_logging to skip taking a snapshot of the given directory.
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Failed to take a snapshot of .. Pass snapshot_directory=None to start_logging to skip taking a snapshot of the given directory."
    }
}
[2022-09-22 13:16:18,004: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-22 13:16:18,004: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-22 13:16:18,006: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 13:16:18,008: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 13:18:07,762: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-22 13:18:24,258: INFO: stage_01_load_n_save_data]: raw data is saved at: artifacts\raw_local_dir\data.csv successfully
[2022-09-22 13:18:24,297: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data completed!<<<<<

[2022-09-22 13:18:50,317: INFO: stage_02_data_preprocessing]: 
********************
[2022-09-22 13:18:50,317: INFO: stage_02_data_preprocessing]: >>>>> stage Data Preprocessing started <<<<<
[2022-09-22 13:18:50,319: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 13:18:50,321: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 13:18:50,321: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-22 13:18:56,541: INFO: clientbase]: Created a worker pool for first use
[2022-09-22 13:19:07,087: ERROR: stage_02_data_preprocessing]: SnapshotException:
	Message: Failed to take a snapshot of .. Pass snapshot_directory=None to start_logging to skip taking a snapshot of the given directory.
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Failed to take a snapshot of .. Pass snapshot_directory=None to start_logging to skip taking a snapshot of the given directory."
    }
}
Traceback (most recent call last):
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\run.py", line 609, in _start_logging
    run.take_snapshot(snapshot_directory)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\run.py", line 2201, in take_snapshot
    return self._client.take_snapshot(file_or_folder_path)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_run_impl\run_history_facade.py", line 706, in take_snapshot
    raise_on_validation_failure=_raise_on_validation_failure)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\snapshots_client.py", line 87, in create_snapshot
    self._validate_snapshot_size(file_or_folder_path, exclude_function, raise_on_validation_failure)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\snapshots_client.py", line 65, in _validate_snapshot_size
    raise SnapshotException(error_message)
azureml.exceptions._azureml_exception.SnapshotException: SnapshotException:
	Message: ====================================================================

While attempting to take snapshot of .
Your total snapshot size exceeds the limit of 300.0 MB.
Please see http://aka.ms/aml-largefiles on how to work with large files.

====================================================================


	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "====================================================================\n\nWhile attempting to take snapshot of .\nYour total snapshot size exceeds the limit of 300.0 MB.\nPlease see http://aka.ms/aml-largefiles on how to work with large files.\n\n====================================================================\n\n"
    }
}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/stage_02_data_preprocessing.py", line 115, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_data_preprocessing.py", line 44, in main
    run = experiment.start_logging()
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\experiment.py", line 279, in start_logging
    return Run._start_logging(self, *args, _parent_logger=self._logger, **kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\run.py", line 613, in _start_logging
    raise_from(SnapshotException(error_msg), snapshot_ex)
  File "<string>", line 3, in raise_from
azureml.exceptions._azureml_exception.SnapshotException: SnapshotException:
	Message: Failed to take a snapshot of .. Pass snapshot_directory=None to start_logging to skip taking a snapshot of the given directory.
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Failed to take a snapshot of .. Pass snapshot_directory=None to start_logging to skip taking a snapshot of the given directory."
    }
}
[2022-09-22 13:25:08,758: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-22 13:25:08,769: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-22 13:25:08,791: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 13:25:08,795: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 13:27:05,723: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-22 13:27:22,679: INFO: stage_01_load_n_save_data]: raw data is saved at: artifacts\raw_local_dir\data.csv successfully
[2022-09-22 13:27:22,723: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data completed!<<<<<

[2022-09-22 13:27:47,888: INFO: stage_02_data_preprocessing]: 
********************
[2022-09-22 13:27:47,888: INFO: stage_02_data_preprocessing]: >>>>> stage Data Preprocessing started <<<<<
[2022-09-22 13:27:47,891: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 13:27:47,893: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 13:27:47,894: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-22 13:27:54,160: INFO: clientbase]: Created a worker pool for first use
[2022-09-22 13:28:07,045: ERROR: stage_02_data_preprocessing]: '>' not supported between instances of 'int' and 'tuple'
Traceback (most recent call last):
  File "src/stage_02_data_preprocessing.py", line 116, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_data_preprocessing.py", line 45, in main
    run = experiment.start_logging()
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\experiment.py", line 279, in start_logging
    return Run._start_logging(self, *args, _parent_logger=self._logger, **kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\run.py", line 609, in _start_logging
    run.take_snapshot(snapshot_directory)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\run.py", line 2201, in take_snapshot
    return self._client.take_snapshot(file_or_folder_path)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_run_impl\run_history_facade.py", line 706, in take_snapshot
    raise_on_validation_failure=_raise_on_validation_failure)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\snapshots_client.py", line 87, in create_snapshot
    self._validate_snapshot_size(file_or_folder_path, exclude_function, raise_on_validation_failure)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\snapshots_client.py", line 53, in _validate_snapshot_size
    size_limit=SNAPSHOT_MAX_SIZE_BYTES, exclude_function=exclude_function)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_file_utils\file_utils.py", line 390, in get_path_size
    file_or_folder_path, size_limit=size_limit, exclude_function=exclude_function)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_file_utils\file_utils.py", line 373, in get_directory_size
    if size_limit and total_size > size_limit:
TypeError: '>' not supported between instances of 'int' and 'tuple'
[2022-09-22 13:28:41,065: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-22 13:28:41,065: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-22 13:28:41,067: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 13:28:41,069: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 13:32:07,712: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-22 13:32:24,485: INFO: stage_01_load_n_save_data]: raw data is saved at: artifacts\raw_local_dir\data.csv successfully
[2022-09-22 13:32:24,524: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data completed!<<<<<

[2022-09-22 13:32:37,245: INFO: stage_02_data_preprocessing]: 
********************
[2022-09-22 13:32:37,245: INFO: stage_02_data_preprocessing]: >>>>> stage Data Preprocessing started <<<<<
[2022-09-22 13:32:37,247: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 13:32:37,249: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 13:32:37,250: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-22 13:32:42,375: INFO: clientbase]: Created a worker pool for first use
[2022-09-22 13:32:57,148: ERROR: stage_02_data_preprocessing]: SnapshotException:
	Message: Failed to take a snapshot of .. Pass snapshot_directory=None to start_logging to skip taking a snapshot of the given directory.
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Failed to take a snapshot of .. Pass snapshot_directory=None to start_logging to skip taking a snapshot of the given directory."
    }
}
Traceback (most recent call last):
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\run.py", line 609, in _start_logging
    run.take_snapshot(snapshot_directory)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\run.py", line 2201, in take_snapshot
    return self._client.take_snapshot(file_or_folder_path)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_run_impl\run_history_facade.py", line 706, in take_snapshot
    raise_on_validation_failure=_raise_on_validation_failure)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\snapshots_client.py", line 87, in create_snapshot
    self._validate_snapshot_size(file_or_folder_path, exclude_function, raise_on_validation_failure)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\snapshots_client.py", line 65, in _validate_snapshot_size
    raise SnapshotException(error_message)
azureml.exceptions._azureml_exception.SnapshotException: SnapshotException:
	Message: ====================================================================

While attempting to take snapshot of .
Your total snapshot size exceeds the limit of 500.0 MB.
Please see http://aka.ms/aml-largefiles on how to work with large files.

====================================================================


	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "====================================================================\n\nWhile attempting to take snapshot of .\nYour total snapshot size exceeds the limit of 500.0 MB.\nPlease see http://aka.ms/aml-largefiles on how to work with large files.\n\n====================================================================\n\n"
    }
}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/stage_02_data_preprocessing.py", line 116, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_data_preprocessing.py", line 45, in main
    run = experiment.start_logging()
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\experiment.py", line 279, in start_logging
    return Run._start_logging(self, *args, _parent_logger=self._logger, **kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\run.py", line 613, in _start_logging
    raise_from(SnapshotException(error_msg), snapshot_ex)
  File "<string>", line 3, in raise_from
azureml.exceptions._azureml_exception.SnapshotException: SnapshotException:
	Message: Failed to take a snapshot of .. Pass snapshot_directory=None to start_logging to skip taking a snapshot of the given directory.
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Failed to take a snapshot of .. Pass snapshot_directory=None to start_logging to skip taking a snapshot of the given directory."
    }
}
[2022-09-22 13:34:09,185: INFO: stage_02_data_preprocessing]: 
********************
[2022-09-22 13:34:09,185: INFO: stage_02_data_preprocessing]: >>>>> stage Data Preprocessing started <<<<<
[2022-09-22 13:34:09,187: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 13:34:09,188: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 13:34:09,189: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-22 13:34:13,922: INFO: clientbase]: Created a worker pool for first use
[2022-09-22 13:38:08,377: ERROR: stage_02_data_preprocessing]: ('Connection aborted.', timeout('The write operation timed out'))
Traceback (most recent call last):
  File "src/stage_02_data_preprocessing.py", line 116, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_data_preprocessing.py", line 45, in main
    run = experiment.start_logging()
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\experiment.py", line 279, in start_logging
    return Run._start_logging(self, *args, _parent_logger=self._logger, **kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\run.py", line 609, in _start_logging
    run.take_snapshot(snapshot_directory)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\run.py", line 2201, in take_snapshot
    return self._client.take_snapshot(file_or_folder_path)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_run_impl\run_history_facade.py", line 706, in take_snapshot
    raise_on_validation_failure=_raise_on_validation_failure)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\snapshots_client.py", line 121, in create_snapshot
    revision_list = self._upload_snapshot_files(entries_to_send, file_or_folder_path, exclude_function)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\snapshots_client.py", line 239, in _upload_snapshot_files
    revision_list = self._upload_files_batch(file_nodes, file_or_folder_path, session)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\snapshots_client.py", line 210, in _upload_files_batch
    revision_list.append(file_revision)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_common\async_utils\task_queue.py", line 55, in __exit__
    self.flush(self.identity)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_common\async_utils\task_queue.py", line 118, in flush
    self._results.extend((task.wait(awaiter_name=self.identity) for task in completed_tasks))
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_common\async_utils\task_queue.py", line 118, in <genexpr>
    self._results.extend((task.wait(awaiter_name=self.identity) for task in completed_tasks))
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_common\async_utils\async_task.py", line 58, in wait
    res = self._handler(self._future, self._logger)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_common\async_utils\async_task.py", line 16, in basic_handler
    return future.result()
  File "D:\BackOrder-Product-Prediction\env\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "D:\BackOrder-Product-Prediction\env\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "D:\BackOrder-Product-Prediction\env\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\snapshots_client.py", line 200, in perform_upload
    backoff=BACKOFF_START, retries=RETRY_LIMIT)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_file_utils\upload.py", line 65, in upload_blob_from_stream
    timeout=timeout, validate_content=True, blob_type="BlockBlob"
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\clientbase.py", line 93, in execute_func_with_reset
    return ClientBase._execute_func_internal(backoff, retries, module_logger, func, reset_func, *args, **kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\clientbase.py", line 367, in _execute_func_internal
    left_retry = cls._handle_retry(back_off, left_retry, total_retry, error, logger, func)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\clientbase.py", line 433, in _handle_retry
    raise error
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\clientbase.py", line 358, in _execute_func_internal
    response = func(*args, **kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azure\core\tracing\decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_vendor\azure_storage\blob\_blob_client.py", line 731, in upload_blob
    return upload_block_blob(**options)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_vendor\azure_storage\blob\_upload_helpers.py", line 165, in upload_block_blob
    **kwargs
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_vendor\azure_storage\blob\_shared\uploads.py", line 79, in upload_data_chunks
    range_ids = [uploader.process_chunk(result) for result in uploader.get_chunk_streams()]
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_vendor\azure_storage\blob\_shared\uploads.py", line 79, in <listcomp>
    range_ids = [uploader.process_chunk(result) for result in uploader.get_chunk_streams()]
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_vendor\azure_storage\blob\_shared\uploads.py", line 195, in process_chunk
    return self._upload_chunk_with_progress(chunk_offset, chunk_bytes)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_vendor\azure_storage\blob\_shared\uploads.py", line 211, in _upload_chunk_with_progress
    range_id = self._upload_chunk(chunk_offset, chunk_data)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_vendor\azure_storage\blob\_shared\uploads.py", line 266, in _upload_chunk
    **self.request_options
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azure\core\tracing\decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_vendor\azure_storage\blob\_generated\operations\_block_blob_operations.py", line 1179, in stage_block
    **kwargs
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azure\core\pipeline\_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 158, in send
    response = self.next.send(request)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_vendor\azure_storage\blob\_shared\policies.py", line 544, in send
    raise err
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_vendor\azure_storage\blob\_shared\policies.py", line 518, in send
    response = self.next.send(request)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_vendor\azure_storage\blob\_shared\policies.py", line 313, in send
    response = self.next.send(request)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azure\core\pipeline\_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_vendor\azure_storage\blob\_shared\base_client.py", line 330, in send
    return self._transport.send(request, **kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azure\core\pipeline\transport\_requests_basic.py", line 361, in send
    raise error
azure.core.exceptions.ServiceResponseError: ('Connection aborted.', timeout('The write operation timed out'))
[2022-09-22 13:42:45,489: INFO: stage_02_data_preprocessing]: 
********************
[2022-09-22 13:42:45,503: INFO: stage_02_data_preprocessing]: >>>>> stage Data Preprocessing started <<<<<
[2022-09-22 13:42:45,533: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 13:42:45,542: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 13:42:45,546: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-22 13:42:51,356: INFO: clientbase]: Created a worker pool for first use
[2022-09-22 13:43:02,700: INFO: run]: Could not load the run context. Logging offline
[2022-09-22 13:43:02,700: INFO: stage_02_data_preprocessing]: fetched the data from : artifacts\raw_local_dir\data.csv
[2022-09-22 13:43:06,476: INFO: stage_02_data_preprocessing]: Dropped last row
[2022-09-22 13:43:07,506: INFO: stage_02_data_preprocessing]: Converted columns to 0's and 1's
[2022-09-22 13:43:07,632: INFO: stage_02_data_preprocessing]: Dropped non imp features from the dataset
[2022-09-22 13:43:07,684: INFO: stage_02_data_preprocessing]: Replacing perf_6_month_avg and perf_12_month_avg with nan values
[2022-09-22 13:43:07,783: INFO: stage_02_data_preprocessing]: Splitting the dataset into X and y
[2022-09-22 13:46:40,580: INFO: stage_02_data_preprocessing]: Filled missing values for lead_time, perf_6_month_avg and perf_12_month_avg columns
[2022-09-22 13:46:41,537: INFO: stage_02_data_preprocessing]: Applying cuberoot for normally distributed data
[2022-09-22 14:03:00,572: INFO: stage_02_data_preprocessing]: Applied Smoteen to handle imbalanceness of data
[2022-09-22 14:03:41,254: INFO: stage_02_data_preprocessing]: Saved the prep data to: artifacts\raw_local_dir\furnished_data.csv
[2022-09-22 14:03:41,447: INFO: stage_02_data_preprocessing]: >>>>> stage Data Preprocessing completed!<<<<<

[2022-09-22 14:04:13,153: INFO: stage_03_train_test_split]: 
********************
[2022-09-22 14:04:13,154: INFO: stage_03_train_test_split]: >>>>> stage Split Data Stage started <<<<<
[2022-09-22 14:04:13,165: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 14:04:13,168: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 14:04:22,736: INFO: stage_03_train_test_split]: splitting of data in training and test files at test_size: 0.2
[2022-09-22 14:04:22,737: INFO: common]: created directory at: artifacts\split_data_dir
[2022-09-22 14:04:58,409: INFO: stage_03_train_test_split]: data is saved at: artifacts\split_data_dir\X_train.csv for X data
[2022-09-22 14:05:06,277: INFO: stage_03_train_test_split]: data is saved at: artifacts\split_data_dir\X_test.csv for X data
[2022-09-22 14:05:08,034: INFO: stage_03_train_test_split]: data is saved at: artifacts\split_data_dir\y_train.csv for y data
[2022-09-22 14:05:08,472: INFO: stage_03_train_test_split]: data is saved at: artifacts\split_data_dir\y_test.csv for y data
[2022-09-22 14:05:08,567: INFO: stage_03_train_test_split]: >>>>> stage Split Data Stage completed!<<<<<

[2022-09-22 14:05:29,992: INFO: stage_04_model_training]: 
********************
[2022-09-22 14:05:29,992: INFO: stage_04_model_training]: >>>>> stage Model Training started <<<<<
[2022-09-22 14:05:29,995: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 14:05:29,996: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 14:05:29,996: INFO: stage_04_model_training]: loaded model parameters
[2022-09-22 14:05:35,866: INFO: stage_04_model_training]: loaded X_train, X_test, y_train, y_test data for model training
[2022-09-22 14:05:35,866: ERROR: stage_04_model_training]: 'MODEL_DIR'
Traceback (most recent call last):
  File "src/stage_04_model_training.py", line 86, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_04_model_training.py", line 53, in main
    model_dir = artifacts["MODEL_DIR"]
KeyError: 'MODEL_DIR'
[2022-09-22 14:11:51,871: INFO: stage_04_model_training]: 
********************
[2022-09-22 14:11:51,871: INFO: stage_04_model_training]: >>>>> stage Model Training started <<<<<
[2022-09-22 14:11:51,873: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 14:11:51,875: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 14:11:51,875: INFO: stage_04_model_training]: loaded model parameters
[2022-09-22 14:11:59,738: INFO: stage_04_model_training]: loaded X_train, X_test, y_train, y_test data for model training
[2022-09-22 14:11:59,739: INFO: common]: created directory at: artifacts\model
[2022-09-22 14:11:59,739: INFO: stage_04_model_training]: Created model directory and loaded model path
[2022-09-22 14:12:01,391: INFO: stage_04_model_training]: Performed Robust Scaling
[2022-09-22 14:12:34,327: INFO: stage_04_model_training]: Completed Model Training
[2022-09-22 14:12:34,393: INFO: stage_04_model_training]: model is trained and saved at: artifacts\model\model.pkl
[2022-09-22 14:12:34,439: INFO: stage_04_model_training]: >>>>> stage Model Training completed!<<<<<

[2022-09-22 14:22:14,738: INFO: stage_04_model_training]: 
********************
[2022-09-22 14:22:14,738: INFO: stage_04_model_training]: >>>>> stage Model Training started <<<<<
[2022-09-22 14:22:14,741: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 14:22:14,742: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 14:22:14,743: INFO: stage_04_model_training]: loaded model parameters
[2022-09-22 14:22:21,852: INFO: stage_04_model_training]: loaded X_train, X_test, y_train, y_test data for model training
[2022-09-22 14:22:21,853: INFO: common]: created directory at: artifacts\model
[2022-09-22 14:22:21,853: INFO: stage_04_model_training]: Created model directory and loaded model path
[2022-09-22 14:22:23,238: INFO: stage_04_model_training]: Performed Robust Scaling
[2022-09-22 14:22:59,685: INFO: stage_04_model_training]: Completed Model Training
[2022-09-22 14:22:59,724: INFO: stage_04_model_training]: model is trained and saved at: artifacts\model\model.pkl
[2022-09-22 14:22:59,789: INFO: stage_04_model_training]: >>>>> stage Model Training completed!<<<<<

[2022-09-22 14:40:11,686: INFO: stage_04_model_training]: 
********************
[2022-09-22 14:40:11,686: INFO: stage_04_model_training]: >>>>> stage Model Training started <<<<<
[2022-09-22 14:40:11,688: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 14:40:11,690: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 14:40:11,691: INFO: stage_04_model_training]: loaded model parameters
[2022-09-22 14:40:19,537: INFO: stage_04_model_training]: loaded X_train, X_test, y_train, y_test data for model training
[2022-09-22 14:40:19,539: INFO: common]: created directory at: artifacts\model_dir
[2022-09-22 14:40:19,539: INFO: stage_04_model_training]: Created model directory and loaded model path
[2022-09-22 14:40:21,052: INFO: stage_04_model_training]: Performed Robust Scaling
[2022-09-22 14:41:03,396: INFO: stage_04_model_training]: Completed Model Training
[2022-09-22 14:41:03,487: INFO: stage_04_model_training]: model is trained and saved at: artifacts\model_dir\model.pkl
[2022-09-22 14:41:03,553: INFO: stage_04_model_training]: >>>>> stage Model Training completed!<<<<<

[2022-09-22 14:51:24,858: INFO: stage_05_evaluate]: 
********************
[2022-09-22 14:51:24,867: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-22 14:51:24,874: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 14:51:24,878: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 14:51:24,881: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-22 14:51:30,409: INFO: clientbase]: Created a worker pool for first use
[2022-09-22 14:51:43,222: INFO: stage_05_evaluate]: loaded X_test, y_test data for model training
[2022-09-22 14:51:44,486: INFO: stage_05_evaluate]: Model loaded
[2022-09-22 14:51:47,855: INFO: stage_05_evaluate]: loaded prediction values
[2022-09-22 14:51:57,943: INFO: common]: json file saved at: scores.json
[2022-09-22 14:51:57,943: INFO: stage_05_evaluate]: Saved the scores in json format
[2022-09-22 14:52:22,838: INFO: stage_05_evaluate]: Run Completed
[2022-09-22 14:52:22,863: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-22 15:02:25,771: INFO: stage_04_model_training]: 
********************
[2022-09-22 15:02:25,771: INFO: stage_04_model_training]: >>>>> stage Model Training started <<<<<
[2022-09-22 15:02:25,774: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 15:02:25,776: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 15:02:25,776: INFO: stage_04_model_training]: loaded model parameters
[2022-09-22 15:02:35,030: INFO: stage_04_model_training]: loaded X_train, X_test, y_train, y_test data for model training
[2022-09-22 15:02:35,032: INFO: stage_04_model_training]: X_train shape: (2604987, 15), X_test shape: (651247, 15), y_train shape: (2604987,), y_test shape: (2604987,)
[2022-09-22 15:02:35,037: INFO: common]: created directory at: artifacts\model_dir
[2022-09-22 15:02:35,037: INFO: stage_04_model_training]: Created model directory and loaded model path
[2022-09-22 15:02:36,637: INFO: stage_04_model_training]: Performed Robust Scaling
[2022-09-22 15:03:05,801: INFO: stage_04_model_training]: Completed Model Training
[2022-09-22 15:03:05,841: INFO: stage_04_model_training]: model is trained and saved at: artifacts\model_dir\model.pkl
[2022-09-22 15:03:05,892: INFO: stage_04_model_training]: >>>>> stage Model Training completed!<<<<<

[2022-09-22 15:29:06,798: INFO: stage_05_evaluate]: 
********************
[2022-09-22 15:29:06,815: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-22 15:29:06,837: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 15:29:06,847: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 15:29:06,850: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-22 15:29:13,249: INFO: clientbase]: Created a worker pool for first use
[2022-09-22 15:29:26,058: INFO: stage_05_evaluate]: loaded X_test, y_test data for model training
[2022-09-22 15:29:26,058: INFO: stage_05_evaluate]: X_test shape: (651247, 15), y_test shape: (651247,)
[2022-09-22 15:29:27,539: INFO: stage_05_evaluate]: Model loaded
[2022-09-22 15:29:30,665: INFO: stage_05_evaluate]: loaded prediction values
[2022-09-22 15:29:40,019: INFO: common]: json file saved at: scores.json
[2022-09-22 15:29:40,020: INFO: stage_05_evaluate]: Saved the scores in json format
[2022-09-22 15:30:01,025: INFO: stage_05_evaluate]: Run Completed
[2022-09-22 15:30:01,025: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-22 19:01:08,889: INFO: stage_04_model_training]: 
********************
[2022-09-22 19:01:08,900: INFO: stage_04_model_training]: >>>>> stage Model Training started <<<<<
[2022-09-22 19:01:08,930: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 19:01:08,947: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 19:01:08,947: INFO: stage_04_model_training]: loaded model parameters
[2022-09-22 19:01:08,947: INFO: stage_04_model_training]: boosting_type: goss,objective: binary,n_estimators:200,n_jobs:-1
[2022-09-22 19:01:17,851: INFO: stage_04_model_training]: loaded X_train, X_test, y_train, y_test data for model training
[2022-09-22 19:01:17,851: INFO: stage_04_model_training]: X_train shape: (2604987, 15), X_test shape: (651247, 15), y_train shape: (2604987,), y_test shape: (651247,)
[2022-09-22 19:01:17,851: INFO: common]: created directory at: artifacts\model_dir
[2022-09-22 19:01:17,851: INFO: stage_04_model_training]: Created model directory and loaded model path
[2022-09-22 19:01:19,697: INFO: stage_04_model_training]: Performed Robust Scaling
[2022-09-22 19:02:02,438: INFO: stage_04_model_training]: Completed Model Training
[2022-09-22 19:02:02,506: INFO: stage_04_model_training]: model is trained and saved at: artifacts\model_dir\model.pkl
[2022-09-22 19:02:02,554: INFO: stage_04_model_training]: >>>>> stage Model Training completed!<<<<<

[2022-09-22 20:16:21,579: INFO: stage_04_model_training]: 
********************
[2022-09-22 20:16:21,586: INFO: stage_04_model_training]: >>>>> stage Model Training started <<<<<
[2022-09-22 20:16:21,600: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 20:16:21,622: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 20:16:21,622: INFO: stage_04_model_training]: loaded model parameters
[2022-09-22 20:16:21,622: INFO: stage_04_model_training]: boosting_type: goss,objective: binary,n_estimators:200,n_jobs:-1
[2022-09-22 20:16:29,920: INFO: stage_04_model_training]: loaded X_train, X_test, y_train, y_test data for model training
[2022-09-22 20:16:29,933: INFO: stage_04_model_training]: X_train shape: (2604987, 15), X_test shape: (651247, 15), y_train shape: (2604987,), y_test shape: (651247,)
[2022-09-22 20:16:29,933: INFO: common]: created directory at: artifacts\model_dir
[2022-09-22 20:16:29,933: INFO: stage_04_model_training]: Created model directory and loaded model path
[2022-09-22 20:16:31,281: INFO: stage_04_model_training]: Performed Robust Scaling
[2022-09-22 20:17:15,422: INFO: stage_04_model_training]: Completed Model Training
[2022-09-22 20:17:15,430: ERROR: stage_04_model_training]: file must have a 'write' attribute
Traceback (most recent call last):
  File "D:\BackOrder-Product-Prediction\env\lib\pickle.py", line 404, in __init__
    self._file_write = file.write
AttributeError: 'str' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/stage_04_model_training.py", line 93, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_04_model_training.py", line 80, in main
    dill.dump(clf, model_file_path)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\dill\_dill.py", line 336, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\dill\_dill.py", line 566, in __init__
    StockPickler.__init__(self, *args, **kwds)
  File "D:\BackOrder-Product-Prediction\env\lib\pickle.py", line 406, in __init__
    raise TypeError("file must have a 'write' attribute")
TypeError: file must have a 'write' attribute
[2022-09-22 20:18:36,476: INFO: stage_04_model_training]: 
********************
[2022-09-22 20:18:36,476: INFO: stage_04_model_training]: >>>>> stage Model Training started <<<<<
[2022-09-22 20:18:36,496: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 20:18:36,501: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 20:18:36,501: INFO: stage_04_model_training]: loaded model parameters
[2022-09-22 20:18:36,501: INFO: stage_04_model_training]: boosting_type: goss,objective: binary,n_estimators:200,n_jobs:-1
[2022-09-22 20:19:02,035: INFO: stage_04_model_training]: loaded X_train, X_test, y_train, y_test data for model training
[2022-09-22 20:19:02,057: INFO: stage_04_model_training]: X_train shape: (2604987, 15), X_test shape: (651247, 15), y_train shape: (2604987,), y_test shape: (651247,)
[2022-09-22 20:19:02,059: INFO: common]: created directory at: artifacts\model_dir
[2022-09-22 20:19:02,059: INFO: stage_04_model_training]: Created model directory and loaded model path
[2022-09-22 20:19:05,984: INFO: stage_04_model_training]: Performed Robust Scaling
[2022-09-22 20:20:00,526: INFO: stage_04_model_training]: Completed Model Training
[2022-09-22 20:20:00,919: ERROR: stage_04_model_training]: write
Traceback (most recent call last):
  File "src/stage_04_model_training.py", line 93, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_04_model_training.py", line 80, in main
    dill.dump(clf, open(model_file_path,'rb'))
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\dill\_dill.py", line 336, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\dill\_dill.py", line 620, in dump
    StockPickler.dump(self, obj)
  File "D:\BackOrder-Product-Prediction\env\lib\pickle.py", line 434, in dump
    self.write(PROTO + pack("<B", self.proto))
  File "D:\BackOrder-Product-Prediction\env\lib\pickle.py", line 229, in write
    return self.file_write(data)
io.UnsupportedOperation: write
[2022-09-22 20:21:51,745: INFO: stage_04_model_training]: 
********************
[2022-09-22 20:21:51,745: INFO: stage_04_model_training]: >>>>> stage Model Training started <<<<<
[2022-09-22 20:21:51,783: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 20:21:51,786: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 20:21:51,787: INFO: stage_04_model_training]: loaded model parameters
[2022-09-22 20:21:51,787: INFO: stage_04_model_training]: boosting_type: goss,objective: binary,n_estimators:200,n_jobs:-1
[2022-09-22 20:21:59,659: INFO: stage_04_model_training]: loaded X_train, X_test, y_train, y_test data for model training
[2022-09-22 20:21:59,659: INFO: stage_04_model_training]: X_train shape: (2604987, 15), X_test shape: (651247, 15), y_train shape: (2604987,), y_test shape: (651247,)
[2022-09-22 20:21:59,659: INFO: common]: created directory at: artifacts\model_dir
[2022-09-22 20:21:59,659: INFO: stage_04_model_training]: Created model directory and loaded model path
[2022-09-22 20:22:01,137: INFO: stage_04_model_training]: Performed Robust Scaling
[2022-09-22 20:22:36,501: INFO: stage_04_model_training]: Completed Model Training
[2022-09-22 20:22:36,545: INFO: stage_04_model_training]: model is trained and saved at: artifacts\model_dir\model.pkl
[2022-09-22 20:22:36,592: INFO: stage_04_model_training]: >>>>> stage Model Training completed!<<<<<

[2022-09-22 20:28:45,922: INFO: stage_05_evaluate]: 
********************
[2022-09-22 20:28:45,922: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-22 20:28:45,934: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 20:28:45,937: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 20:28:45,952: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-22 20:28:54,117: INFO: clientbase]: Created a worker pool for first use
[2022-09-22 20:29:05,427: INFO: stage_05_evaluate]: loaded X_test, y_test data for model training
[2022-09-22 20:29:05,427: INFO: stage_05_evaluate]: X_test shape: (651247, 15), y_test shape: (651247,)
[2022-09-22 20:29:06,502: INFO: stage_05_evaluate]: Model loaded
[2022-09-22 20:29:13,304: INFO: stage_05_evaluate]: loaded prediction values
[2022-09-22 20:29:22,059: INFO: common]: json file saved at: scores.json
[2022-09-22 20:29:22,061: INFO: stage_05_evaluate]: Saved the scores in json format
[2022-09-22 20:29:33,455: INFO: stage_05_evaluate]: Run Completed
[2022-09-22 20:29:33,456: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-22 20:35:13,550: INFO: stage_05_evaluate]: 
********************
[2022-09-22 20:35:13,564: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-22 20:35:13,588: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 20:35:13,609: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 20:35:13,639: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-22 20:35:18,518: INFO: clientbase]: Created a worker pool for first use
[2022-09-22 20:35:29,963: INFO: stage_05_evaluate]: loaded X_test, y_test data for model training
[2022-09-22 20:35:29,964: INFO: stage_05_evaluate]: X_test shape: (651247, 15), y_test shape: (651247,)
[2022-09-22 20:35:31,293: INFO: stage_05_evaluate]: Model loaded
[2022-09-22 20:35:41,782: INFO: stage_05_evaluate]: loaded prediction values
[2022-09-22 20:35:48,369: INFO: stage_05_evaluate]:               precision    recall  f1-score   support

           0       0.57      0.99      0.72    328386
           1       0.97      0.23      0.37    322861

    accuracy                           0.61    651247
   macro avg       0.77      0.61      0.54    651247
weighted avg       0.76      0.61      0.55    651247

[2022-09-22 20:35:55,590: INFO: common]: json file saved at: scores.json
[2022-09-22 20:35:55,590: INFO: stage_05_evaluate]: Saved the scores in json format
[2022-09-22 20:36:13,299: INFO: stage_05_evaluate]: Run Completed
[2022-09-22 20:36:13,299: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-22 21:26:02,721: INFO: stage_04_model_training]: 
********************
[2022-09-22 21:26:02,737: INFO: stage_04_model_training]: >>>>> stage Model Training started <<<<<
[2022-09-22 21:26:02,763: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 21:26:02,792: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 21:26:02,794: INFO: stage_04_model_training]: loaded model parameters
[2022-09-22 21:26:02,794: INFO: stage_04_model_training]: boosting_type: goss,objective: binary,n_estimators:200,n_jobs:-1
[2022-09-22 21:26:14,229: INFO: stage_04_model_training]: loaded X_train, X_test, y_train, y_test data for model training
[2022-09-22 21:26:14,230: INFO: stage_04_model_training]: X_train shape: (2604987, 15), X_test shape: (651247, 15), y_train shape: (2604987,), y_test shape: (651247,)
[2022-09-22 21:26:14,230: INFO: common]: created directory at: artifacts\model_dir
[2022-09-22 21:26:14,230: INFO: stage_04_model_training]: Created model directory and loaded model path
[2022-09-22 21:26:16,206: INFO: stage_04_model_training]: Performed Robust Scaling
[2022-09-22 21:27:03,036: INFO: stage_04_model_training]: Completed Model Training
[2022-09-22 21:27:03,085: INFO: stage_04_model_training]: model is trained and saved at: artifacts\model_dir\model.pkl
[2022-09-22 21:27:03,147: INFO: stage_04_model_training]: >>>>> stage Model Training completed!<<<<<

[2022-09-22 21:30:13,930: INFO: stage_05_evaluate]: 
********************
[2022-09-22 21:30:13,931: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-22 21:30:13,944: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 21:30:13,946: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 21:30:13,947: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-22 21:30:18,108: INFO: clientbase]: Created a worker pool for first use
[2022-09-22 21:30:28,440: INFO: stage_05_evaluate]: loaded X_test, y_test data for model training
[2022-09-22 21:30:28,440: INFO: stage_05_evaluate]: X_test shape: (651247, 15), y_test shape: (651247,)
[2022-09-22 21:30:29,431: INFO: stage_05_evaluate]: Model loaded
[2022-09-22 21:30:32,246: INFO: stage_05_evaluate]: loaded prediction values
[2022-09-22 21:30:36,063: INFO: stage_05_evaluate]:               precision    recall  f1-score   support

           0       0.57      0.99      0.72    328386
           1       0.97      0.23      0.37    322861

    accuracy                           0.61    651247
   macro avg       0.77      0.61      0.54    651247
weighted avg       0.76      0.61      0.55    651247

[2022-09-22 21:30:42,366: INFO: common]: json file saved at: scores.json
[2022-09-22 21:30:42,366: INFO: stage_05_evaluate]: Saved the scores in json format
[2022-09-22 21:30:53,724: INFO: stage_05_evaluate]: Run Completed
[2022-09-22 21:30:53,725: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-22 21:37:37,891: INFO: stage_04_model_training]: 
********************
[2022-09-22 21:37:37,919: INFO: stage_04_model_training]: >>>>> stage Model Training started <<<<<
[2022-09-22 21:37:37,943: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 21:37:37,947: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 21:37:37,948: INFO: stage_04_model_training]: loaded model parameters
[2022-09-22 21:37:37,949: INFO: stage_04_model_training]: boosting_type: goss,objective: binary,n_estimators:200,n_jobs:-1
[2022-09-22 21:37:53,131: INFO: stage_04_model_training]: loaded X_train, X_test, y_train, y_test data for model training
[2022-09-22 21:37:53,132: INFO: stage_04_model_training]: X_train shape: (2604987, 15), X_test shape: (651247, 15), y_train shape: (2604987,), y_test shape: (651247,)
[2022-09-22 21:37:53,133: INFO: common]: created directory at: artifacts\model_dir
[2022-09-22 21:37:53,133: INFO: stage_04_model_training]: Created model directory and loaded model path
[2022-09-22 21:37:55,130: INFO: stage_04_model_training]: Performed Robust Scaling
[2022-09-22 21:38:35,197: INFO: stage_04_model_training]: Completed Model Training
[2022-09-22 21:38:35,241: INFO: stage_04_model_training]: model is trained and saved at: artifacts\model_dir\model.pkl
[2022-09-22 21:38:41,510: INFO: stage_04_model_training]: >>>>> stage Model Training completed!<<<<<

[2022-09-22 21:43:34,376: INFO: stage_04_model_training]: 
********************
[2022-09-22 21:43:34,383: INFO: stage_04_model_training]: >>>>> stage Model Training started <<<<<
[2022-09-22 21:43:34,391: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 21:43:34,393: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 21:43:34,394: INFO: stage_04_model_training]: loaded model parameters
[2022-09-22 21:43:34,394: INFO: stage_04_model_training]: boosting_type: goss,objective: binary,n_estimators:200,n_jobs:-1
[2022-09-22 21:43:41,962: INFO: stage_04_model_training]: loaded X_train, X_test, y_train, y_test data for model training
[2022-09-22 21:43:41,962: INFO: stage_04_model_training]: X_train shape: (2604987, 15), X_test shape: (651247, 15), y_train shape: (2604987,), y_test shape: (651247,)
[2022-09-22 21:43:41,962: INFO: common]: created directory at: artifacts\model_dir
[2022-09-22 21:43:41,962: INFO: stage_04_model_training]: Created model directory and loaded model path
[2022-09-22 21:43:43,348: INFO: stage_04_model_training]: Performed Robust Scaling
[2022-09-22 21:44:18,878: INFO: stage_04_model_training]: Completed Model Training
[2022-09-22 21:44:18,900: INFO: stage_04_model_training]: model is trained and saved at: artifacts\model_dir\model.pkl
[2022-09-22 21:44:25,464: INFO: stage_04_model_training]: >>>>> stage Model Training completed!<<<<<

[2022-09-22 21:47:23,410: INFO: stage_05_evaluate]: 
********************
[2022-09-22 21:47:23,410: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-22 21:47:23,422: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 21:47:23,425: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 21:47:23,442: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-22 21:47:29,023: INFO: clientbase]: Created a worker pool for first use
[2022-09-22 21:47:38,907: INFO: stage_05_evaluate]: loaded X_test, y_test data for model training
[2022-09-22 21:47:38,907: INFO: stage_05_evaluate]: X_test shape: (651247, 15), y_test shape: (651247,)
[2022-09-22 21:47:39,913: INFO: stage_05_evaluate]: Model loaded
[2022-09-22 21:47:42,589: INFO: stage_05_evaluate]: loaded prediction values
[2022-09-22 21:47:45,598: INFO: stage_05_evaluate]:               precision    recall  f1-score   support

           0       0.57      0.99      0.72    328386
           1       0.97      0.23      0.37    322861

    accuracy                           0.61    651247
   macro avg       0.77      0.61      0.54    651247
weighted avg       0.76      0.61      0.55    651247

[2022-09-22 21:47:52,491: INFO: common]: json file saved at: scores.json
[2022-09-22 21:47:52,491: INFO: stage_05_evaluate]: Saved the scores in json format
[2022-09-22 21:48:03,282: INFO: stage_05_evaluate]: Run Completed
[2022-09-22 21:48:03,282: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-22 22:21:10,895: INFO: stage_05_evaluate]: 
********************
[2022-09-22 22:21:10,901: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-22 22:21:10,921: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 22:21:10,941: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 22:21:10,980: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-22 22:21:16,959: INFO: clientbase]: Created a worker pool for first use
[2022-09-22 22:21:39,332: INFO: stage_05_evaluate]: loaded X_test, y_test data for model training
[2022-09-22 22:21:39,335: INFO: stage_05_evaluate]: X_test shape: (651247, 15), y_test shape: (651247,)
[2022-09-22 22:21:48,691: INFO: stage_05_evaluate]: Model loaded
[2022-09-22 22:21:48,692: INFO: stage_05_evaluate]: loaded prediction values
[2022-09-22 22:21:52,813: INFO: stage_05_evaluate]:               precision    recall  f1-score   support

           0       0.57      0.99      0.72    328386
           1       0.97      0.23      0.37    322861

    accuracy                           0.61    651247
   macro avg       0.77      0.61      0.54    651247
weighted avg       0.76      0.61      0.55    651247

[2022-09-22 22:22:01,972: INFO: common]: json file saved at: scores.json
[2022-09-22 22:22:01,973: INFO: stage_05_evaluate]: Saved the scores in json format
[2022-09-22 22:22:14,132: INFO: stage_05_evaluate]: Run Completed
[2022-09-22 22:22:14,132: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-22 22:30:48,992: INFO: stage_05_evaluate]: 
********************
[2022-09-22 22:30:48,993: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-22 22:30:49,012: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 22:30:49,017: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 22:30:49,019: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-22 22:30:53,308: INFO: clientbase]: Created a worker pool for first use
[2022-09-22 22:31:11,128: INFO: stage_05_evaluate]: loaded X_test, y_test data for model training
[2022-09-22 22:31:11,128: INFO: stage_05_evaluate]: X_test shape: (651247, 15), y_test shape: (651247,)
[2022-09-22 22:31:17,373: INFO: stage_05_evaluate]: Model loaded
[2022-09-22 22:31:17,373: INFO: stage_05_evaluate]: loaded prediction values
[2022-09-22 22:31:19,659: INFO: stage_05_evaluate]:               precision    recall  f1-score   support

           0       0.57      0.99      0.72    328386
           1       0.97      0.23      0.37    322861

    accuracy                           0.61    651247
   macro avg       0.77      0.61      0.54    651247
weighted avg       0.76      0.61      0.55    651247

[2022-09-22 22:31:26,159: INFO: common]: json file saved at: scores.json
[2022-09-22 22:31:26,160: INFO: stage_05_evaluate]: Saved the scores in json format
[2022-09-22 22:31:38,965: INFO: stage_05_evaluate]: Run Completed
[2022-09-22 22:31:38,966: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-22 22:37:03,152: INFO: stage_05_evaluate]: 
********************
[2022-09-22 22:37:03,152: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-22 22:37:03,168: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-22 22:37:03,177: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-22 22:37:12,230: INFO: stage_05_evaluate]: loaded X_test, y_test data for model training
[2022-09-22 22:37:12,230: INFO: stage_05_evaluate]: X_test shape: (651247, 15), y_test shape: (651247,)
[2022-09-22 22:37:18,491: INFO: stage_05_evaluate]: Model loaded
[2022-09-22 22:37:18,491: INFO: stage_05_evaluate]: loaded prediction values
[2022-09-22 22:37:20,399: INFO: stage_05_evaluate]:               precision    recall  f1-score   support

           0       0.57      0.99      0.72    328386
           1       0.97      0.23      0.37    322861

    accuracy                           0.61    651247
   macro avg       0.77      0.61      0.54    651247
weighted avg       0.76      0.61      0.55    651247

[2022-09-22 22:37:20,423: INFO: common]: json file saved at: scores.json
[2022-09-22 22:37:20,423: INFO: stage_05_evaluate]: Saved the scores in json format
[2022-09-22 22:37:20,424: INFO: stage_05_evaluate]: Run Completed
[2022-09-22 22:37:20,467: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-23 11:16:05,987: INFO: stage_05_evaluate]: 
********************
[2022-09-23 11:16:06,003: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-23 11:16:06,039: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 11:16:06,049: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 11:16:16,565: INFO: stage_05_evaluate]: loaded X_test, y_test data for model training
[2022-09-23 11:16:16,587: INFO: stage_05_evaluate]: X_test shape: (651247, 15), y_test shape: (651247,)
[2022-09-23 11:16:25,017: INFO: stage_05_evaluate]: Model loaded
[2022-09-23 11:16:25,017: INFO: stage_05_evaluate]: loaded prediction values
[2022-09-23 11:16:26,959: INFO: stage_05_evaluate]:               precision    recall  f1-score   support

           0       0.57      0.99      0.72    328386
           1       0.97      0.23      0.37    322861

    accuracy                           0.61    651247
   macro avg       0.77      0.61      0.54    651247
weighted avg       0.76      0.61      0.55    651247

[2022-09-23 11:16:27,065: INFO: common]: json file saved at: scores.json
[2022-09-23 11:16:27,065: INFO: stage_05_evaluate]: Saved the scores in json format
[2022-09-23 11:16:27,066: INFO: stage_05_evaluate]: Run Completed
[2022-09-23 11:16:27,127: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-23 11:23:01,221: INFO: stage_05_evaluate]: 
********************
[2022-09-23 11:23:01,233: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-23 11:23:01,252: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 11:23:01,257: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 11:23:09,652: INFO: stage_05_evaluate]: loaded X_test, y_test data for model training
[2022-09-23 11:23:09,652: INFO: stage_05_evaluate]: X_test shape: (651247, 15), y_test shape: (651247,)
[2022-09-23 11:23:15,255: INFO: stage_05_evaluate]: Model loaded
[2022-09-23 11:23:15,256: INFO: stage_05_evaluate]: loaded prediction values
[2022-09-23 11:23:17,011: INFO: stage_05_evaluate]:               precision    recall  f1-score   support

           0       0.57      0.99      0.72    328386
           1       0.97      0.23      0.37    322861

    accuracy                           0.61    651247
   macro avg       0.77      0.61      0.54    651247
weighted avg       0.76      0.61      0.55    651247

[2022-09-23 11:23:17,013: INFO: common]: json file saved at: scores.json
[2022-09-23 11:23:17,013: INFO: stage_05_evaluate]: Saved the scores in json format
[2022-09-23 11:23:17,013: INFO: stage_05_evaluate]: Run Completed
[2022-09-23 11:23:17,046: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-23 12:03:18,034: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-23 12:03:18,037: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-23 12:03:18,053: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 12:03:18,055: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 12:10:49,679: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-23 12:11:28,868: INFO: stage_01_load_n_save_data]: raw data is saved at: artifacts\raw_local_dir\data.csv successfully
[2022-09-23 12:11:28,917: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data completed!<<<<<

[2022-09-23 12:23:58,124: INFO: stage_05_evaluate]: 
********************
[2022-09-23 12:23:58,136: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-23 12:23:58,155: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 12:23:58,159: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 12:24:07,417: INFO: stage_05_evaluate]: loaded X_test, y_test data for model training
[2022-09-23 12:24:07,418: INFO: stage_05_evaluate]: X_test shape: (651247, 15), y_test shape: (651247,)
[2022-09-23 12:24:14,122: INFO: stage_05_evaluate]: Model loaded
[2022-09-23 12:24:14,122: INFO: stage_05_evaluate]: loaded prediction values
[2022-09-23 12:24:16,723: INFO: stage_05_evaluate]:               precision    recall  f1-score   support

           0       0.57      0.99      0.72    328386
           1       0.97      0.23      0.37    322861

    accuracy                           0.61    651247
   macro avg       0.77      0.61      0.54    651247
weighted avg       0.76      0.61      0.55    651247

[2022-09-23 12:24:16,724: INFO: common]: json file saved at: scores.json
[2022-09-23 12:24:16,724: INFO: stage_05_evaluate]: Saved the scores in json format
[2022-09-23 12:24:16,724: INFO: stage_05_evaluate]: Run Completed
[2022-09-23 12:24:16,756: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-23 12:36:21,487: INFO: stage_05_evaluate]: 
********************
[2022-09-23 12:36:21,488: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-23 12:36:21,515: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 12:36:21,517: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 12:36:28,377: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-23 12:37:13,812: INFO: stage_05_evaluate]: 
********************
[2022-09-23 12:37:13,812: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-23 12:37:13,814: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 12:37:13,816: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 12:37:19,306: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-23 12:37:56,617: INFO: stage_05_evaluate]: 
********************
[2022-09-23 12:37:56,617: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-23 12:37:56,619: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 12:37:56,620: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 12:38:00,825: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-23 12:38:28,619: INFO: stage_05_evaluate]: 
********************
[2022-09-23 12:38:28,619: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-23 12:38:28,621: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 12:38:28,623: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 12:38:32,878: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-23 12:42:14,287: INFO: stage_05_evaluate]: 
********************
[2022-09-23 12:42:14,298: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-23 12:42:14,298: ERROR: stage_05_evaluate]: main() missing 1 required positional argument: 'params_path'
Traceback (most recent call last):
  File "src/stage_05_evaluate.py", line 50, in <module>
    main(config_path=parsed_args.config)
TypeError: main() missing 1 required positional argument: 'params_path'
[2022-09-23 12:42:45,511: INFO: stage_05_evaluate]: 
********************
[2022-09-23 12:42:45,511: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-23 12:42:45,623: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 12:42:53,080: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-23 12:44:40,993: INFO: stage_05_evaluate]: 
********************
[2022-09-23 12:44:40,993: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-23 12:44:40,996: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 12:44:46,176: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-23 12:51:29,461: INFO: stage_05_evaluate]: 
********************
[2022-09-23 12:51:29,461: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-23 12:51:29,463: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 12:51:34,667: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-23 12:52:48,040: INFO: stage_05_evaluate]: 
********************
[2022-09-23 12:52:48,040: INFO: stage_05_evaluate]: >>>>> stage Evaluate started <<<<<
[2022-09-23 12:52:48,043: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 12:52:53,311: INFO: stage_05_evaluate]: >>>>> stage Evaluate completed!<<<<<

[2022-09-23 13:09:42,686: INFO: stage_05_evaluate]: 
********************
[2022-09-23 13:09:42,700: INFO: stage_05_evaluate]: >>>>> stage Evaluate  started <<<<<
[2022-09-23 13:09:42,700: ERROR: stage_05_evaluate]: main() got an unexpected keyword argument 'params_path'
Traceback (most recent call last):
  File "src/stage_05_evaluate.py", line 58, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
TypeError: main() got an unexpected keyword argument 'params_path'
[2022-09-23 13:10:18,583: INFO: stage_05_evaluate]: 
********************
[2022-09-23 13:10:18,583: INFO: stage_05_evaluate]: >>>>> stage Evaluate  started <<<<<
[2022-09-23 13:10:18,689: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 13:10:20,858: ERROR: stage_05_evaluate]: module 'dill' has no attribute 'load_model'
Traceback (most recent call last):
  File "src/stage_05_evaluate.py", line 57, in <module>
    main(config_path=parsed_args.config)
  File "src/stage_05_evaluate.py", line 37, in main
    mdl = dill.load_model(open('artifacts/model_dir/model.pkl','rb'))
AttributeError: module 'dill' has no attribute 'load_model'
[2022-09-23 13:10:48,901: INFO: stage_05_evaluate]: 
********************
[2022-09-23 13:10:48,901: INFO: stage_05_evaluate]: >>>>> stage Evaluate  started <<<<<
[2022-09-23 13:10:48,904: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 13:10:56,496: INFO: stage_05_evaluate]: >>>>> stage Evaluate  completed!<<<<<

[2022-09-23 13:21:16,537: INFO: stage_05_evaluate]: 
********************
[2022-09-23 13:21:16,554: INFO: stage_05_evaluate]: >>>>> stage Evaluate  started <<<<<
[2022-09-23 13:21:16,562: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 13:21:24,597: INFO: stage_05_evaluate]: >>>>> stage Evaluate  completed!<<<<<

[2022-09-23 13:23:25,440: INFO: stage_03_train_test_split]: 
********************
[2022-09-23 13:23:25,440: INFO: stage_03_train_test_split]: >>>>> stage Split Data Stage started <<<<<
[2022-09-23 13:23:25,443: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 13:23:25,445: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 13:23:39,289: INFO: stage_03_train_test_split]: splitting of data in training and test files at test_size: 0.2
[2022-09-23 13:23:39,312: INFO: common]: created directory at: artifacts\split_data_dir
[2022-09-23 13:24:18,200: INFO: stage_03_train_test_split]: data is saved at: artifacts\split_data_dir\X_train.csv for X data
[2022-09-23 13:24:27,421: INFO: stage_03_train_test_split]: data is saved at: artifacts\split_data_dir\X_test.csv for X data
[2022-09-23 13:24:29,484: INFO: stage_03_train_test_split]: data is saved at: artifacts\split_data_dir\y_train.csv for y data
[2022-09-23 13:24:30,120: INFO: stage_03_train_test_split]: data is saved at: artifacts\split_data_dir\y_test.csv for y data
[2022-09-23 13:24:30,265: INFO: stage_03_train_test_split]: >>>>> stage Split Data Stage completed!<<<<<

[2022-09-23 13:25:56,136: INFO: stage_05_evaluate]: 
********************
[2022-09-23 13:25:56,137: INFO: stage_05_evaluate]: >>>>> stage Evaluate  started <<<<<
[2022-09-23 13:25:56,181: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 13:26:02,862: INFO: stage_05_evaluate]: >>>>> stage Evaluate  completed!<<<<<

[2022-09-23 13:59:22,634: INFO: stage_04_model_training]: 
********************
[2022-09-23 13:59:22,643: INFO: stage_04_model_training]: >>>>> stage Model Training & Evaluate started <<<<<
[2022-09-23 13:59:22,651: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 13:59:22,661: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 13:59:22,679: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-23 13:59:27,925: INFO: clientbase]: Created a worker pool for first use
[2022-09-23 13:59:37,821: INFO: stage_04_model_training]: loaded model parameters
[2022-09-23 13:59:37,821: INFO: stage_04_model_training]: boosting_type: goss,objective: binary,n_estimators:200,n_jobs:-1
[2022-09-23 13:59:51,404: INFO: stage_04_model_training]: loaded X_train, X_test, y_train, y_test data for model training
[2022-09-23 13:59:51,404: INFO: stage_04_model_training]: X_train shape: (2604704, 15), X_test shape: (651177, 15), y_train shape: (2604704,), y_test shape: (651177,)
[2022-09-23 13:59:51,406: INFO: common]: created directory at: artifacts\model_dir
[2022-09-23 13:59:51,406: INFO: stage_04_model_training]: Created model directory and loaded model path
[2022-09-23 13:59:53,751: INFO: stage_04_model_training]: Performed Robust Scaling
[2022-09-23 14:00:30,729: INFO: stage_04_model_training]: Completed Model Training
[2022-09-23 14:00:30,854: INFO: stage_04_model_training]: model is trained and saved at: artifacts\model_dir\model.pkl
[2022-09-23 14:00:38,333: INFO: common]: json file saved at: scores.json
[2022-09-23 14:00:38,333: INFO: stage_04_model_training]: Saved the scores in json format
[2022-09-23 14:01:01,545: INFO: stage_04_model_training]: Run Completed
[2022-09-23 14:01:01,545: INFO: stage_04_model_training]: >>>>> stage Model Training & Evaluate completed!<<<<<

[2022-09-23 14:05:59,800: INFO: stage_04_model_training]: 
********************
[2022-09-23 14:05:59,800: INFO: stage_04_model_training]: >>>>> stage Model Training & Evaluate started <<<<<
[2022-09-23 14:05:59,808: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 14:05:59,811: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 14:05:59,812: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-23 14:06:02,839: INFO: clientbase]: Created a worker pool for first use
[2022-09-23 14:06:09,926: ERROR: stage_04_model_training]: SnapshotException:
	Message: Failed to take a snapshot of .. Pass snapshot_directory=None to start_logging to skip taking a snapshot of the given directory.
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Failed to take a snapshot of .. Pass snapshot_directory=None to start_logging to skip taking a snapshot of the given directory."
    }
}
Traceback (most recent call last):
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\run.py", line 609, in _start_logging
    run.take_snapshot(snapshot_directory)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\run.py", line 2201, in take_snapshot
    return self._client.take_snapshot(file_or_folder_path)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_run_impl\run_history_facade.py", line 706, in take_snapshot
    raise_on_validation_failure=_raise_on_validation_failure)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\snapshots_client.py", line 87, in create_snapshot
    self._validate_snapshot_size(file_or_folder_path, exclude_function, raise_on_validation_failure)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\_restclient\snapshots_client.py", line 65, in _validate_snapshot_size
    raise SnapshotException(error_message)
azureml.exceptions._azureml_exception.SnapshotException: SnapshotException:
	Message: ====================================================================

While attempting to take snapshot of .
Your total snapshot size exceeds the limit of 300.0 MB.
Please see http://aka.ms/aml-largefiles on how to work with large files.

====================================================================


	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "====================================================================\n\nWhile attempting to take snapshot of .\nYour total snapshot size exceeds the limit of 300.0 MB.\nPlease see http://aka.ms/aml-largefiles on how to work with large files.\n\n====================================================================\n\n"
    }
}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/stage_04_model_training.py", line 133, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_04_model_training.py", line 38, in main
    run = experiment.start_logging()
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\experiment.py", line 279, in start_logging
    return Run._start_logging(self, *args, _parent_logger=self._logger, **kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\azureml\core\run.py", line 613, in _start_logging
    raise_from(SnapshotException(error_msg), snapshot_ex)
  File "<string>", line 3, in raise_from
azureml.exceptions._azureml_exception.SnapshotException: SnapshotException:
	Message: Failed to take a snapshot of .. Pass snapshot_directory=None to start_logging to skip taking a snapshot of the given directory.
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Failed to take a snapshot of .. Pass snapshot_directory=None to start_logging to skip taking a snapshot of the given directory."
    }
}
[2022-09-23 14:13:04,963: INFO: stage_04_model_training]: 
********************
[2022-09-23 14:13:04,963: INFO: stage_04_model_training]: >>>>> stage Model Training & Evaluate started <<<<<
[2022-09-23 14:13:04,964: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 14:13:04,966: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 14:13:04,967: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-23 14:13:08,739: INFO: clientbase]: Created a worker pool for first use
[2022-09-23 14:13:14,333: INFO: stage_04_model_training]: loaded model parameters
[2022-09-23 14:13:14,333: INFO: stage_04_model_training]: boosting_type: goss,objective: binary,n_estimators:200,n_jobs:-1
[2022-09-23 14:13:22,613: INFO: stage_04_model_training]: loaded X_train, X_test, y_train, y_test data for model training
[2022-09-23 14:13:22,632: INFO: stage_04_model_training]: X_train shape: (2604704, 15), X_test shape: (651177, 15), y_train shape: (2604704,), y_test shape: (651177,)
[2022-09-23 14:13:22,633: INFO: common]: created directory at: artifacts\model_dir
[2022-09-23 14:13:22,633: INFO: stage_04_model_training]: Created model directory and loaded model path
[2022-09-23 14:13:25,759: INFO: stage_04_model_training]: Performed Robust Scaling
[2022-09-23 14:13:53,209: INFO: stage_04_model_training]: Completed Model Training
[2022-09-23 14:13:53,239: INFO: stage_04_model_training]: model is trained and saved at: artifacts\model_dir\model.pkl
[2022-09-23 14:13:56,586: INFO: stage_04_model_training]: loading model for prediction
[2022-09-23 14:13:58,522: INFO: stage_04_model_training]: Calculating Model metrics
[2022-09-23 14:13:58,565: INFO: stage_04_model_training]: Recall: 0.9764560482959209, Precision: 0.9686550332930806, F1-Score: 0.9725398975143686
[2022-09-23 14:13:58,568: INFO: common]: json file saved at: scores.json
[2022-09-23 14:13:58,568: INFO: stage_04_model_training]: Saved the scores in json format
[2022-09-23 14:14:10,611: INFO: stage_04_model_training]: Run Completed
[2022-09-23 14:14:10,611: INFO: stage_04_model_training]: >>>>> stage Model Training & Evaluate completed!<<<<<

[2022-09-23 14:17:23,023: INFO: stage_04_model_training]: 
********************
[2022-09-23 14:17:23,023: INFO: stage_04_model_training]: >>>>> stage Model Training & Evaluate started <<<<<
[2022-09-23 14:17:23,035: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 14:17:23,037: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 14:17:23,038: INFO: workspace]: Found the config file in: D:\BackOrder-Product-Prediction\config.json
[2022-09-23 14:17:26,960: INFO: clientbase]: Created a worker pool for first use
[2022-09-23 14:17:32,654: INFO: stage_04_model_training]: loaded model parameters
[2022-09-23 14:17:32,654: INFO: stage_04_model_training]: boosting_type: goss,objective: binary,n_estimators:200,n_jobs:-1
[2022-09-23 14:17:39,792: INFO: stage_04_model_training]: loaded X_train, X_test, y_train, y_test data for model training
[2022-09-23 14:17:39,794: INFO: stage_04_model_training]: X_train shape: (2604704, 15), X_test shape: (651177, 15), y_train shape: (2604704,), y_test shape: (651177,)
[2022-09-23 14:17:39,794: INFO: common]: created directory at: artifacts\model_dir
[2022-09-23 14:17:39,794: INFO: stage_04_model_training]: Created model directory and loaded model path
[2022-09-23 14:17:41,188: INFO: stage_04_model_training]: Performed Robust Scaling
[2022-09-23 14:18:07,415: INFO: stage_04_model_training]: Completed Model Training
[2022-09-23 14:18:07,425: INFO: stage_04_model_training]: model is trained and saved at: artifacts\model_dir\model.pkl
[2022-09-23 14:18:10,715: INFO: stage_04_model_training]: loading model for prediction
[2022-09-23 14:18:12,799: INFO: stage_04_model_training]: Calculating Model metrics
[2022-09-23 14:18:12,925: INFO: stage_04_model_training]: Recall: 0.9764560482959209, Precision: 0.9686550332930806, F1-Score: 0.9725398975143686
[2022-09-23 14:18:12,927: INFO: common]: json file saved at: scores.json
[2022-09-23 14:18:12,927: INFO: stage_04_model_training]: Saved the scores in json format
[2022-09-23 14:18:24,093: INFO: stage_04_model_training]: Run Completed
[2022-09-23 14:18:24,093: INFO: stage_04_model_training]: >>>>> stage Model Training & Evaluate completed!<<<<<

[2022-09-23 19:03:50,991: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-23 19:03:51,012: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-23 19:03:51,038: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 19:03:51,056: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 19:03:51,058: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-23 19:03:52,453: INFO: stage_01_load_n_save_data]: raw data is saved at: artifacts\raw_local_dir\data.csv successfully
[2022-09-23 19:03:52,453: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data completed!<<<<<

[2022-09-23 19:09:09,298: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-23 19:09:09,305: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-23 19:09:09,323: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 19:09:09,334: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 19:09:09,335: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-23 19:09:10,707: ERROR: stage_01_load_n_save_data]: local variable 'zipfile' referenced before assignment
Traceback (most recent call last):
  File "src/stage_01_load_n_save_data.py", line 59, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_load_n_save_data.py", line 43, in main
    zipfile= zipfile.ZipFile(BytesIO(req.content))
UnboundLocalError: local variable 'zipfile' referenced before assignment
[2022-09-23 19:10:15,268: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-23 19:10:15,268: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-23 19:10:15,270: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 19:10:15,272: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 19:10:15,272: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-23 19:10:16,660: ERROR: stage_01_load_n_save_data]: File is not a zip file
Traceback (most recent call last):
  File "src/stage_01_load_n_save_data.py", line 59, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_load_n_save_data.py", line 43, in main
    zf = zipfile.ZipFile(BytesIO(req.content))
  File "D:\BackOrder-Product-Prediction\env\lib\zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "D:\BackOrder-Product-Prediction\env\lib\zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2022-09-23 19:20:20,474: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-23 19:20:20,485: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-23 19:20:20,501: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 19:20:20,504: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 19:20:20,505: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-23 19:20:21,672: ERROR: stage_01_load_n_save_data]: File is not a zip file
Traceback (most recent call last):
  File "src/stage_01_load_n_save_data.py", line 59, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_load_n_save_data.py", line 43, in main
    with zipfile.ZipFile('backorder_data.zip','r') as zip_file:
  File "D:\BackOrder-Product-Prediction\env\lib\zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "D:\BackOrder-Product-Prediction\env\lib\zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2022-09-23 19:25:50,959: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-23 19:25:50,963: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-23 19:25:50,989: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 19:25:50,996: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 19:25:50,997: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-23 19:25:52,609: ERROR: stage_01_load_n_save_data]: backorder_data.zip is not a zip file
Traceback (most recent call last):
  File "src/stage_01_load_n_save_data.py", line 58, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_load_n_save_data.py", line 43, in main
    shutil.unpack_archive('backorder_data.zip','artifacts/raw_local_dir')
  File "D:\BackOrder-Product-Prediction\env\lib\shutil.py", line 1002, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\shutil.py", line 899, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: backorder_data.zip is not a zip file
[2022-09-23 19:26:29,829: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-23 19:26:29,829: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-23 19:26:29,837: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-23 19:26:29,843: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-23 19:26:29,843: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-23 19:26:31,010: ERROR: stage_01_load_n_save_data]: backorder_data.zip is not a zip file
Traceback (most recent call last):
  File "src/stage_01_load_n_save_data.py", line 58, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_load_n_save_data.py", line 43, in main
    shutil.unpack_archive('backorder_data.zip','artifacts/raw_local_dir/')
  File "D:\BackOrder-Product-Prediction\env\lib\shutil.py", line 1002, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "D:\BackOrder-Product-Prediction\env\lib\shutil.py", line 899, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: backorder_data.zip is not a zip file
[2022-09-25 12:27:08,369: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-25 12:27:08,404: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-25 12:27:08,452: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-25 12:27:08,476: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-25 12:39:27,882: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-25 12:39:27,882: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-25 12:39:27,884: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-25 12:39:27,886: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-25 12:40:05,612: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-25 12:40:09,721: INFO: stage_01_load_n_save_data]: raw data is saved at: artifacts\raw_local_dir\data.csv successfully
[2022-09-25 12:40:09,773: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data completed!<<<<<

[2022-09-26 09:26:05,787: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-26 09:26:05,808: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-26 09:26:05,840: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-26 09:26:05,850: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-26 09:28:03,819: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-26 09:28:12,199: INFO: stage_01_load_n_save_data]: raw data is saved at: artifacts\raw_local_dir\data.csv successfully
[2022-09-26 09:28:12,284: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data completed!<<<<<

[2022-09-26 09:30:18,574: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-26 09:30:18,574: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-26 09:30:18,591: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-26 09:30:18,593: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-26 09:31:11,030: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-26 09:31:20,472: INFO: stage_01_load_n_save_data]: raw data is saved at: artifacts\raw_local_dir\data.csv successfully
[2022-09-26 09:31:20,581: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data completed!<<<<<

[2022-09-26 09:33:48,612: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-26 09:33:48,612: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-26 09:33:48,630: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-26 09:33:48,635: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-26 09:35:14,140: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-26 09:35:14,154: INFO: stage_01_load_n_save_data]:   sku,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,min_bank,potential_issue,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
0  1026827,0,,0,0,0,0,0,0,0,0,0,No,0,-99,-99,0,No...                                                                                                                                                                                                                                                                      
1  1043384,2,9,0,0,0,0,0,0,0,0,0,No,0,0.990,0.990...                                                                                                                                                                                                                                                                      
2  1043696,2,,0,0,0,0,0,0,0,0,0,No,0,-99,-99,0,Ye...                                                                                                                                                                                                                                                                      
[2022-09-26 09:35:18,550: INFO: stage_01_load_n_save_data]: raw data is saved at: artifacts\raw_local_dir\data.csv successfully
[2022-09-26 09:35:18,642: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data completed!<<<<<

[2022-09-26 09:38:01,950: INFO: stage_02_data_preprocessing]: 
********************
[2022-09-26 09:38:01,951: INFO: stage_02_data_preprocessing]: >>>>> stage Data Preprocessing started <<<<<
[2022-09-26 09:38:01,971: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-26 09:38:01,975: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-26 09:38:01,976: INFO: stage_02_data_preprocessing]: fetched the data from : artifacts\raw_local_dir\data.csv
[2022-09-26 09:38:07,284: ERROR: stage_02_data_preprocessing]: 'potential_issue'
Traceback (most recent call last):
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'potential_issue'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/stage_02_data_preprocessing.py", line 121, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_data_preprocessing.py", line 54, in main
    print(df['potential_issue'].unique())
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'potential_issue'
[2022-09-26 09:40:46,611: INFO: stage_02_data_preprocessing]: 
********************
[2022-09-26 09:40:46,616: INFO: stage_02_data_preprocessing]: >>>>> stage Data Preprocessing started <<<<<
[2022-09-26 09:40:46,631: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-26 09:40:46,636: INFO: common]: yaml file: params.yaml loaded successfully
[2022-09-26 09:40:46,636: INFO: stage_02_data_preprocessing]: fetched the data from : artifacts\raw_local_dir\data.csv
[2022-09-26 09:40:50,853: ERROR: stage_02_data_preprocessing]: 'potential_issue'
Traceback (most recent call last):
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'potential_issue'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/stage_02_data_preprocessing.py", line 121, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_02_data_preprocessing.py", line 54, in main
    print(df['potential_issue'].unique())
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "D:\BackOrder-Product-Prediction\env\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'potential_issue'
[2022-09-26 10:45:41,379: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-26 10:45:41,386: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-26 10:45:41,386: ERROR: stage_01_load_n_save_data]: main() got an unexpected keyword argument 'params_path'
Traceback (most recent call last):
  File "src/stage_01_load_n_save_data.py", line 50, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
TypeError: main() got an unexpected keyword argument 'params_path'
[2022-09-26 10:45:59,983: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-26 10:45:59,983: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-26 10:45:59,983: ERROR: stage_01_load_n_save_data]: main() got an unexpected keyword argument 'params_path'
Traceback (most recent call last):
  File "src/stage_01_load_n_save_data.py", line 50, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
TypeError: main() got an unexpected keyword argument 'params_path'
[2022-09-26 10:46:32,722: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-26 10:46:32,722: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-26 10:46:32,835: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-26 10:47:35,681: INFO: stage_01_load_n_save_data]: Shape of the data is: (1687861, 1)
[2022-09-26 10:47:35,682: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-26 10:47:40,032: INFO: stage_01_load_n_save_data]: raw data is saved at: artifacts\raw_local_dir\data.csv
[2022-09-26 10:47:40,084: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data completed!<<<<<

[2022-09-26 10:57:45,159: INFO: stage_01_load_n_save_data]: 
********************
[2022-09-26 10:57:45,159: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data started <<<<<
[2022-09-26 10:57:45,165: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-09-26 10:58:31,101: INFO: stage_01_load_n_save_data]: Shape of the data is: (1687861, 23)
[2022-09-26 10:58:31,108: INFO: common]: created directory at: artifacts\raw_local_dir
[2022-09-26 10:58:47,651: INFO: stage_01_load_n_save_data]: raw data is saved at: artifacts\raw_local_dir\data.csv
[2022-09-26 10:58:47,718: INFO: stage_01_load_n_save_data]: >>>>> stage Get and Save Data completed!<<<<<

